# Docker Compose for Development with Hot Reload

services:
  mongodb:
    image: mongo:7.0
    container_name: vietjet_mongodb_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: vietjet_clone
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - vietjet_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vietjet_backend_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/vietjet_clone?authSource=admin
      JWT_SECRET: dev-jwt-secret
      JWT_REFRESH_SECRET: dev-refresh-secret
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - vietjet_network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vietjet_frontend_dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - vietjet_network
    command: npm run dev

networks:
  vietjet_network:
    driver: bridge

volumes:
  mongodb_data_dev:
    driver: local
